### YamlMime:ManagedReference
items:
- uid: WebApplication.UserPages.UserHome.TeacherNavTab
  commentId: T:WebApplication.UserPages.UserHome.TeacherNavTab
  id: UserHome.TeacherNavTab
  parent: WebApplication.UserPages
  children:
  - WebApplication.UserPages.UserHome.TeacherNavTab.Home
  - WebApplication.UserPages.UserHome.TeacherNavTab.None
  - WebApplication.UserPages.UserHome.TeacherNavTab.Tasks
  langs:
  - csharp
  - vb
  name: UserHome.TeacherNavTab
  nameWithType: UserHome.TeacherNavTab
  fullName: WebApplication.UserPages.UserHome.TeacherNavTab
  type: Enum
  source:
    remote:
      path: WebApplication/UserPages/UserHome.Master.cs
      branch: FerMod
      repo: git@github.com:FerMod/HADSProject.git
    id: TeacherNavTab
    path: ../WebApplication/UserPages/UserHome.Master.cs
    startLine: 21
  assemblies:
  - WebApplication
  namespace: WebApplication.UserPages
  syntax:
    content: public enum TeacherNavTab
    content.vb: Public Enum TeacherNavTab
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: WebApplication.UserPages.UserHome.TeacherNavTab.None
  commentId: F:WebApplication.UserPages.UserHome.TeacherNavTab.None
  id: None
  parent: WebApplication.UserPages.UserHome.TeacherNavTab
  langs:
  - csharp
  - vb
  name: None
  nameWithType: UserHome.TeacherNavTab.None
  fullName: WebApplication.UserPages.UserHome.TeacherNavTab.None
  type: Field
  source:
    remote:
      path: WebApplication/UserPages/UserHome.Master.cs
      branch: FerMod
      repo: git@github.com:FerMod/HADSProject.git
    id: None
    path: ../WebApplication/UserPages/UserHome.Master.cs
    startLine: 22
  assemblies:
  - WebApplication
  namespace: WebApplication.UserPages
  syntax:
    content: None = -1
    return:
      type: WebApplication.UserPages.UserHome.TeacherNavTab
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: WebApplication.UserPages.UserHome.TeacherNavTab.Home
  commentId: F:WebApplication.UserPages.UserHome.TeacherNavTab.Home
  id: Home
  parent: WebApplication.UserPages.UserHome.TeacherNavTab
  langs:
  - csharp
  - vb
  name: Home
  nameWithType: UserHome.TeacherNavTab.Home
  fullName: WebApplication.UserPages.UserHome.TeacherNavTab.Home
  type: Field
  source:
    remote:
      path: WebApplication/UserPages/UserHome.Master.cs
      branch: FerMod
      repo: git@github.com:FerMod/HADSProject.git
    id: Home
    path: ../WebApplication/UserPages/UserHome.Master.cs
    startLine: 23
  assemblies:
  - WebApplication
  namespace: WebApplication.UserPages
  syntax:
    content: Home = 0
    return:
      type: WebApplication.UserPages.UserHome.TeacherNavTab
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: WebApplication.UserPages.UserHome.TeacherNavTab.Tasks
  commentId: F:WebApplication.UserPages.UserHome.TeacherNavTab.Tasks
  id: Tasks
  parent: WebApplication.UserPages.UserHome.TeacherNavTab
  langs:
  - csharp
  - vb
  name: Tasks
  nameWithType: UserHome.TeacherNavTab.Tasks
  fullName: WebApplication.UserPages.UserHome.TeacherNavTab.Tasks
  type: Field
  source:
    remote:
      path: WebApplication/UserPages/UserHome.Master.cs
      branch: FerMod
      repo: git@github.com:FerMod/HADSProject.git
    id: Tasks
    path: ../WebApplication/UserPages/UserHome.Master.cs
    startLine: 24
  assemblies:
  - WebApplication
  namespace: WebApplication.UserPages
  syntax:
    content: Tasks = 1
    return:
      type: WebApplication.UserPages.UserHome.TeacherNavTab
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: WebApplication.UserPages
  commentId: N:WebApplication.UserPages
  name: WebApplication.UserPages
  nameWithType: WebApplication.UserPages
  fullName: WebApplication.UserPages
- uid: WebApplication.UserPages.UserHome.TeacherNavTab
  commentId: T:WebApplication.UserPages.UserHome.TeacherNavTab
  parent: WebApplication.UserPages
  name: UserHome.TeacherNavTab
  nameWithType: UserHome.TeacherNavTab
  fullName: WebApplication.UserPages.UserHome.TeacherNavTab
