### YamlMime:ManagedReference
items:
- uid: WebApplication
  commentId: N:WebApplication
  id: WebApplication
  children:
  - WebApplication._Default
  - WebApplication.About
  - WebApplication.Account
  - WebApplication.Account.ActiveNav
  - WebApplication.AppConfig
  - WebApplication.AppConfig.Json
  - WebApplication.AppConfig.SmtpServer
  - WebApplication.AppConfig.WebSite
  - WebApplication.AppConfig.Xml
  - WebApplication.BundleConfig
  - WebApplication.CambiarPassword
  - WebApplication.Confirmar
  - WebApplication.Contact
  - WebApplication.EmailSent
  - WebApplication.Global
  - WebApplication.Inicio
  - WebApplication.RedirectPage
  - WebApplication.Registro
  - WebApplication.RouteConfig
  - WebApplication.ScriptResource
  - WebApplication.Site_Mobile
  - WebApplication.SiteMaster
  - WebApplication.ViewSwitcher
  - WebApplication.WebAlertNotification
  langs:
  - csharp
  - vb
  name: WebApplication
  nameWithType: WebApplication
  fullName: WebApplication
  type: Namespace
  assemblies:
  - WebApplication
references:
- uid: WebApplication.Account
  commentId: T:WebApplication.Account
  parent: WebApplication
  name: Account
  nameWithType: Account
  fullName: WebApplication.Account
- uid: WebApplication.Account.ActiveNav
  commentId: T:WebApplication.Account.ActiveNav
  parent: WebApplication
  name: Account.ActiveNav
  nameWithType: Account.ActiveNav
  fullName: WebApplication.Account.ActiveNav
- uid: WebApplication.AppConfig
  commentId: T:WebApplication.AppConfig
  name: AppConfig
  nameWithType: AppConfig
  fullName: WebApplication.AppConfig
- uid: WebApplication.AppConfig.WebSite
  commentId: T:WebApplication.AppConfig.WebSite
  name: AppConfig.WebSite
  nameWithType: AppConfig.WebSite
  fullName: WebApplication.AppConfig.WebSite
- uid: WebApplication.AppConfig.SmtpServer
  commentId: T:WebApplication.AppConfig.SmtpServer
  name: AppConfig.SmtpServer
  nameWithType: AppConfig.SmtpServer
  fullName: WebApplication.AppConfig.SmtpServer
- uid: WebApplication.AppConfig.Xml
  commentId: T:WebApplication.AppConfig.Xml
  name: AppConfig.Xml
  nameWithType: AppConfig.Xml
  fullName: WebApplication.AppConfig.Xml
- uid: WebApplication.AppConfig.Json
  commentId: T:WebApplication.AppConfig.Json
  name: AppConfig.Json
  nameWithType: AppConfig.Json
  fullName: WebApplication.AppConfig.Json
- uid: WebApplication.BundleConfig
  commentId: T:WebApplication.BundleConfig
  name: BundleConfig
  nameWithType: BundleConfig
  fullName: WebApplication.BundleConfig
- uid: WebApplication.About
  commentId: T:WebApplication.About
  name: About
  nameWithType: About
  fullName: WebApplication.About
- uid: WebApplication.ScriptResource
  commentId: T:WebApplication.ScriptResource
  name: ScriptResource
  nameWithType: ScriptResource
  fullName: WebApplication.ScriptResource
- uid: WebApplication.RouteConfig
  commentId: T:WebApplication.RouteConfig
  name: RouteConfig
  nameWithType: RouteConfig
  fullName: WebApplication.RouteConfig
- uid: WebApplication.CambiarPassword
  commentId: T:WebApplication.CambiarPassword
  name: CambiarPassword
  nameWithType: CambiarPassword
  fullName: WebApplication.CambiarPassword
- uid: WebApplication.Confirmar
  commentId: T:WebApplication.Confirmar
  name: Confirmar
  nameWithType: Confirmar
  fullName: WebApplication.Confirmar
- uid: WebApplication.EmailSent
  commentId: T:WebApplication.EmailSent
  name: EmailSent
  nameWithType: EmailSent
  fullName: WebApplication.EmailSent
- uid: WebApplication.Contact
  commentId: T:WebApplication.Contact
  name: Contact
  nameWithType: Contact
  fullName: WebApplication.Contact
- uid: WebApplication._Default
  commentId: T:WebApplication._Default
  name: _Default
  nameWithType: _Default
  fullName: WebApplication._Default
- uid: WebApplication.Global
  commentId: T:WebApplication.Global
  name: Global
  nameWithType: Global
  fullName: WebApplication.Global
- uid: WebApplication.Inicio
  commentId: T:WebApplication.Inicio
  name: Inicio
  nameWithType: Inicio
  fullName: WebApplication.Inicio
- uid: WebApplication.RedirectPage
  commentId: T:WebApplication.RedirectPage
  name: RedirectPage
  nameWithType: RedirectPage
  fullName: WebApplication.RedirectPage
- uid: WebApplication.Registro
  commentId: T:WebApplication.Registro
  name: Registro
  nameWithType: Registro
  fullName: WebApplication.Registro
- uid: WebApplication.SiteMaster
  commentId: T:WebApplication.SiteMaster
  parent: WebApplication
  name: SiteMaster
  nameWithType: SiteMaster
  fullName: WebApplication.SiteMaster
- uid: WebApplication.Site_Mobile
  commentId: T:WebApplication.Site_Mobile
  name: Site_Mobile
  nameWithType: Site_Mobile
  fullName: WebApplication.Site_Mobile
- uid: WebApplication.ViewSwitcher
  commentId: T:WebApplication.ViewSwitcher
  name: ViewSwitcher
  nameWithType: ViewSwitcher
  fullName: WebApplication.ViewSwitcher
- uid: WebApplication.WebAlertNotification
  commentId: T:WebApplication.WebAlertNotification
  name: WebAlertNotification
  nameWithType: WebAlertNotification
  fullName: WebApplication.WebAlertNotification
- uid: WebApplication
  commentId: N:WebApplication
  name: WebApplication
  nameWithType: WebApplication
  fullName: WebApplication
