### YamlMime:ManagedReference
items:
- uid: WebApplication.UserPages
  commentId: N:WebApplication.UserPages
  id: WebApplication.UserPages
  children:
  - WebApplication.UserPages.ExportarTareas
  - WebApplication.UserPages.ImportarTareasDataSet
  - WebApplication.UserPages.ImportarTareasXmlDocument
  - WebApplication.UserPages.InsertarTarea
  - WebApplication.UserPages.InstanciarTarea
  - WebApplication.UserPages.Student
  - WebApplication.UserPages.StudentHome
  - WebApplication.UserPages.StudentMenu
  - WebApplication.UserPages.TareasAlumno
  - WebApplication.UserPages.TareasProfesor
  - WebApplication.UserPages.Teacher
  - WebApplication.UserPages.TeacherHome
  - WebApplication.UserPages.TeacherMenu
  langs:
  - csharp
  - vb
  name: WebApplication.UserPages
  nameWithType: WebApplication.UserPages
  fullName: WebApplication.UserPages
  type: Namespace
  assemblies:
  - WebApplication
references:
- uid: WebApplication.UserPages.StudentHome
  commentId: T:WebApplication.UserPages.StudentHome
  name: StudentHome
  nameWithType: StudentHome
  fullName: WebApplication.UserPages.StudentHome
- uid: WebApplication.UserPages.StudentMenu
  commentId: T:WebApplication.UserPages.StudentMenu
  parent: WebApplication.UserPages
  name: StudentMenu
  nameWithType: StudentMenu
  fullName: WebApplication.UserPages.StudentMenu
- uid: WebApplication.UserPages.Student
  commentId: T:WebApplication.UserPages.Student
  parent: WebApplication.UserPages
  name: Student
  nameWithType: Student
  fullName: WebApplication.UserPages.Student
- uid: WebApplication.UserPages.ImportarTareasDataSet
  commentId: T:WebApplication.UserPages.ImportarTareasDataSet
  name: ImportarTareasDataSet
  nameWithType: ImportarTareasDataSet
  fullName: WebApplication.UserPages.ImportarTareasDataSet
- uid: WebApplication.UserPages.InsertarTarea
  commentId: T:WebApplication.UserPages.InsertarTarea
  name: InsertarTarea
  nameWithType: InsertarTarea
  fullName: WebApplication.UserPages.InsertarTarea
- uid: WebApplication.UserPages.InstanciarTarea
  commentId: T:WebApplication.UserPages.InstanciarTarea
  name: InstanciarTarea
  nameWithType: InstanciarTarea
  fullName: WebApplication.UserPages.InstanciarTarea
- uid: WebApplication.UserPages.ImportarTareasXmlDocument
  commentId: T:WebApplication.UserPages.ImportarTareasXmlDocument
  name: ImportarTareasXmlDocument
  nameWithType: ImportarTareasXmlDocument
  fullName: WebApplication.UserPages.ImportarTareasXmlDocument
- uid: WebApplication.UserPages.ExportarTareas
  commentId: T:WebApplication.UserPages.ExportarTareas
  name: ExportarTareas
  nameWithType: ExportarTareas
  fullName: WebApplication.UserPages.ExportarTareas
- uid: WebApplication.UserPages.TeacherHome
  commentId: T:WebApplication.UserPages.TeacherHome
  name: TeacherHome
  nameWithType: TeacherHome
  fullName: WebApplication.UserPages.TeacherHome
- uid: WebApplication.UserPages.TareasProfesor
  commentId: T:WebApplication.UserPages.TareasProfesor
  name: TareasProfesor
  nameWithType: TareasProfesor
  fullName: WebApplication.UserPages.TareasProfesor
- uid: WebApplication.UserPages.TareasAlumno
  commentId: T:WebApplication.UserPages.TareasAlumno
  name: TareasAlumno
  nameWithType: TareasAlumno
  fullName: WebApplication.UserPages.TareasAlumno
- uid: WebApplication.UserPages.TeacherMenu
  commentId: T:WebApplication.UserPages.TeacherMenu
  parent: WebApplication.UserPages
  name: TeacherMenu
  nameWithType: TeacherMenu
  fullName: WebApplication.UserPages.TeacherMenu
- uid: WebApplication.UserPages.Teacher
  commentId: T:WebApplication.UserPages.Teacher
  parent: WebApplication.UserPages
  name: Teacher
  nameWithType: Teacher
  fullName: WebApplication.UserPages.Teacher
- uid: WebApplication.UserPages
  commentId: N:WebApplication.UserPages
  name: WebApplication.UserPages
  nameWithType: WebApplication.UserPages
  fullName: WebApplication.UserPages
