### YamlMime:ManagedReference
items:
- uid: WebApplication.Framework
  commentId: N:WebApplication.Framework
  id: WebApplication.Framework
  children:
  - WebApplication.Framework.AlertLevel
  - WebApplication.Framework.AppSecurity
  - WebApplication.Framework.ConnectedUsersTrack
  - WebApplication.Framework.NotificationData
  - WebApplication.Framework.ParametizedUrl
  - WebApplication.Framework.Query
  - WebApplication.Framework.Query.GenericTasks
  - WebApplication.Framework.UserRole
  - WebApplication.Framework.UserType
  langs:
  - csharp
  - vb
  name: WebApplication.Framework
  nameWithType: WebApplication.Framework
  fullName: WebApplication.Framework
  type: Namespace
  assemblies:
  - WebApplication
references:
- uid: WebApplication.Framework.AppSecurity
  commentId: T:WebApplication.Framework.AppSecurity
  name: AppSecurity
  nameWithType: AppSecurity
  fullName: WebApplication.Framework.AppSecurity
- uid: WebApplication.Framework.ConnectedUsersTrack
  commentId: T:WebApplication.Framework.ConnectedUsersTrack
  parent: WebApplication.Framework
  name: ConnectedUsersTrack
  nameWithType: ConnectedUsersTrack
  fullName: WebApplication.Framework.ConnectedUsersTrack
- uid: WebApplication.Framework.UserType
  commentId: T:WebApplication.Framework.UserType
  parent: WebApplication.Framework
  name: UserType
  nameWithType: UserType
  fullName: WebApplication.Framework.UserType
- uid: WebApplication.Framework.UserRole
  commentId: T:WebApplication.Framework.UserRole
  parent: WebApplication.Framework
  name: UserRole
  nameWithType: UserRole
  fullName: WebApplication.Framework.UserRole
- uid: WebApplication.Framework.AlertLevel
  commentId: T:WebApplication.Framework.AlertLevel
  parent: WebApplication.Framework
  name: AlertLevel
  nameWithType: AlertLevel
  fullName: WebApplication.Framework.AlertLevel
- uid: WebApplication.Framework.NotificationData
  commentId: T:WebApplication.Framework.NotificationData
  parent: WebApplication.Framework
  name: NotificationData
  nameWithType: NotificationData
  fullName: WebApplication.Framework.NotificationData
- uid: WebApplication.Framework.ParametizedUrl
  commentId: T:WebApplication.Framework.ParametizedUrl
  parent: WebApplication.Framework
  name: ParametizedUrl
  nameWithType: ParametizedUrl
  fullName: WebApplication.Framework.ParametizedUrl
- uid: WebApplication.Framework.Query
  commentId: T:WebApplication.Framework.Query
  name: Query
  nameWithType: Query
  fullName: WebApplication.Framework.Query
- uid: WebApplication.Framework.Query.GenericTasks
  commentId: T:WebApplication.Framework.Query.GenericTasks
  name: Query.GenericTasks
  nameWithType: Query.GenericTasks
  fullName: WebApplication.Framework.Query.GenericTasks
- uid: WebApplication.Framework
  commentId: N:WebApplication.Framework
  name: WebApplication.Framework
  nameWithType: WebApplication.Framework
  fullName: WebApplication.Framework
