### YamlMime:ManagedReference
items:
- uid: WebApplication.UserPages.UserHome.ActiveNavTab
  commentId: T:WebApplication.UserPages.UserHome.ActiveNavTab
  id: UserHome.ActiveNavTab
  parent: WebApplication.UserPages
  children:
  - WebApplication.UserPages.UserHome.ActiveNavTab.Home
  - WebApplication.UserPages.UserHome.ActiveNavTab.None
  - WebApplication.UserPages.UserHome.ActiveNavTab.Tasks
  langs:
  - csharp
  - vb
  name: UserHome.ActiveNavTab
  nameWithType: UserHome.ActiveNavTab
  fullName: WebApplication.UserPages.UserHome.ActiveNavTab
  type: Enum
  source:
    remote:
      path: WebApplication/UserPages/UserHome.Master.cs
      branch: FerMod
      repo: git@github.com:FerMod/HADSProject.git
    id: ActiveNavTab
    path: ../WebApplication/UserPages/UserHome.Master.cs
    startLine: 14
  assemblies:
  - WebApplication
  namespace: WebApplication.UserPages
  syntax:
    content: public enum ActiveNavTab
    content.vb: Public Enum ActiveNavTab
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: WebApplication.UserPages.UserHome.ActiveNavTab.None
  commentId: F:WebApplication.UserPages.UserHome.ActiveNavTab.None
  id: None
  parent: WebApplication.UserPages.UserHome.ActiveNavTab
  langs:
  - csharp
  - vb
  name: None
  nameWithType: UserHome.ActiveNavTab.None
  fullName: WebApplication.UserPages.UserHome.ActiveNavTab.None
  type: Field
  source:
    remote:
      path: WebApplication/UserPages/UserHome.Master.cs
      branch: FerMod
      repo: git@github.com:FerMod/HADSProject.git
    id: None
    path: ../WebApplication/UserPages/UserHome.Master.cs
    startLine: 15
  assemblies:
  - WebApplication
  namespace: WebApplication.UserPages
  syntax:
    content: None = -1
    return:
      type: WebApplication.UserPages.UserHome.ActiveNavTab
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: WebApplication.UserPages.UserHome.ActiveNavTab.Home
  commentId: F:WebApplication.UserPages.UserHome.ActiveNavTab.Home
  id: Home
  parent: WebApplication.UserPages.UserHome.ActiveNavTab
  langs:
  - csharp
  - vb
  name: Home
  nameWithType: UserHome.ActiveNavTab.Home
  fullName: WebApplication.UserPages.UserHome.ActiveNavTab.Home
  type: Field
  source:
    remote:
      path: WebApplication/UserPages/UserHome.Master.cs
      branch: FerMod
      repo: git@github.com:FerMod/HADSProject.git
    id: Home
    path: ../WebApplication/UserPages/UserHome.Master.cs
    startLine: 16
  assemblies:
  - WebApplication
  namespace: WebApplication.UserPages
  syntax:
    content: Home = 0
    return:
      type: WebApplication.UserPages.UserHome.ActiveNavTab
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: WebApplication.UserPages.UserHome.ActiveNavTab.Tasks
  commentId: F:WebApplication.UserPages.UserHome.ActiveNavTab.Tasks
  id: Tasks
  parent: WebApplication.UserPages.UserHome.ActiveNavTab
  langs:
  - csharp
  - vb
  name: Tasks
  nameWithType: UserHome.ActiveNavTab.Tasks
  fullName: WebApplication.UserPages.UserHome.ActiveNavTab.Tasks
  type: Field
  source:
    remote:
      path: WebApplication/UserPages/UserHome.Master.cs
      branch: FerMod
      repo: git@github.com:FerMod/HADSProject.git
    id: Tasks
    path: ../WebApplication/UserPages/UserHome.Master.cs
    startLine: 17
  assemblies:
  - WebApplication
  namespace: WebApplication.UserPages
  syntax:
    content: Tasks = 1
    return:
      type: WebApplication.UserPages.UserHome.ActiveNavTab
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: WebApplication.UserPages
  commentId: N:WebApplication.UserPages
  name: WebApplication.UserPages
  nameWithType: WebApplication.UserPages
  fullName: WebApplication.UserPages
- uid: WebApplication.UserPages.UserHome.ActiveNavTab
  commentId: T:WebApplication.UserPages.UserHome.ActiveNavTab
  parent: WebApplication.UserPages
  name: UserHome.ActiveNavTab
  nameWithType: UserHome.ActiveNavTab
  fullName: WebApplication.UserPages.UserHome.ActiveNavTab
