### YamlMime:ManagedReference
items:
- uid: WebApplication.UserPage
  commentId: N:WebApplication.UserPage
  id: WebApplication.UserPage
  children:
  - WebApplication.UserPage.InstanciarTarea
  - WebApplication.UserPage.TareasAlumno
  langs:
  - csharp
  - vb
  name: WebApplication.UserPage
  nameWithType: WebApplication.UserPage
  fullName: WebApplication.UserPage
  type: Namespace
  assemblies:
  - WebApplication
references:
- uid: WebApplication.UserPage.InstanciarTarea
  commentId: T:WebApplication.UserPage.InstanciarTarea
  name: InstanciarTarea
  nameWithType: InstanciarTarea
  fullName: WebApplication.UserPage.InstanciarTarea
- uid: WebApplication.UserPage.TareasAlumno
  commentId: T:WebApplication.UserPage.TareasAlumno
  name: TareasAlumno
  nameWithType: TareasAlumno
  fullName: WebApplication.UserPage.TareasAlumno
