### YamlMime:ManagedReference
items:
- uid: WebApplication.Framework
  commentId: N:WebApplication.Framework
  id: WebApplication.Framework
  children:
  - WebApplication.Framework.AlertLevel
  - WebApplication.Framework.NotificationData
  - WebApplication.Framework.ParametizedUrl
  - WebApplication.Framework.Query
  langs:
  - csharp
  - vb
  name: WebApplication.Framework
  nameWithType: WebApplication.Framework
  fullName: WebApplication.Framework
  type: Namespace
  assemblies:
  - WebApplication
references:
- uid: WebApplication.Framework.AlertLevel
  commentId: T:WebApplication.Framework.AlertLevel
  parent: WebApplication.Framework
  name: AlertLevel
  nameWithType: AlertLevel
  fullName: WebApplication.Framework.AlertLevel
- uid: WebApplication.Framework.NotificationData
  commentId: T:WebApplication.Framework.NotificationData
  parent: WebApplication.Framework
  name: NotificationData
  nameWithType: NotificationData
  fullName: WebApplication.Framework.NotificationData
- uid: WebApplication.Framework.ParametizedUrl
  commentId: T:WebApplication.Framework.ParametizedUrl
  parent: WebApplication.Framework
  name: ParametizedUrl
  nameWithType: ParametizedUrl
  fullName: WebApplication.Framework.ParametizedUrl
- uid: WebApplication.Framework.Query
  commentId: T:WebApplication.Framework.Query
  name: Query
  nameWithType: Query
  fullName: WebApplication.Framework.Query
- uid: WebApplication.Framework
  commentId: N:WebApplication.Framework
  name: WebApplication.Framework
  nameWithType: WebApplication.Framework
  fullName: WebApplication.Framework
